defaultPortal: hubspot-ones-theme
portals:
  - name: hubspot-ones-theme
    portalId: 22593806
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CJSXtviuMBIJAA0AAAAA4A0DGI6C4wog1eegFiju6QwyFFWqQ7cEiSbtaORqSldZapYcV1A9OjcAAARBAAAAeAAAAAAAAAAAAAAAAAAAAAQAAMAHAP7_MTwAAAYAAABgAAAAAAAAAAAAAAAAADACQhTRa9SJqUyOY3y7X4I6qZC1GMrDZ0oDbmExUgBaAA
        expiresAt: '2022-08-30T14:00:18.583Z'
    personalAccessKey: >-
      CiRiMjcwYzEzZC1kOTI2LTQ0ZWItYmI2YS03YjJlOTJkYTQ4YTcQjoLjChjV56AWKhkABeaRgmLqzKev8VcGIazHMzgnGKK-L-ajSgNuYTE
    sandboxAccountType: null
    parentAccountId: null
