defaultPortal: hubspot-ones-theme
portals:
  - name: hubspot-ones-theme
    portalId: 22593806
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          COXN5vKuMBIJAA0AAAAA4A0DGI6C4wog1eegFiju6QwyFBosgFwFSLmw_syJiRmrrAtFzxXLOjcAAARBAAAAeAAAAAAAAAAAAAAAAAAAAAQAAMAHAP7_MTwAAAYAAABgAAAAAAAAAAAAAAAAADACQhTZu4oGW_YVa9nrRBffjlyJNvkQwkoDbmExUgBaAA
        expiresAt: '2022-08-30T10:43:49.095Z'
    personalAccessKey: >-
      CiRiMjcwYzEzZC1kOTI2LTQ0ZWItYmI2YS03YjJlOTJkYTQ4YTcQjoLjChjV56AWKhkABeaRgmLqzKev8VcGIazHMzgnGKK-L-ajSgNuYTE
    sandboxAccountType: null
    parentAccountId: null
