defaultPortal: ones-hubspot-theme
portals:
  - name: ones-hubspot-theme
    portalId: 22593806
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CLqhkb2xMBIJAA0AAAAA4A0DGI6C4wog1eegFiju6QwyFCq9uLJd5Fqyc_rqpDutGQdwuFxWOjcAAARBAAAAeAAAAAAAAAAAAAAAAAAAAAQAAMAHAP7_MTwAAAYAAABgAAAAAAAAAAAAAAAAADACQhSTgFOizrd4TAxhwnhxQvvZ51Kw8koDbmExUgBaAA
        expiresAt: '2022-09-07T11:09:48.093Z'
    personalAccessKey: >-
      CiRiMjcwYzEzZC1kOTI2LTQ0ZWItYmI2YS03YjJlOTJkYTQ4YTcQjoLjChjV56AWKhkABeaRgmLqzKev8VcGIazHMzgnGKK-L-ajSgNuYTE
    sandboxAccountType: null
    parentAccountId: null
